FEATURE_MAP = {
    1: "history",
    2: "info",
    3: "actions",
    4: "dividends",
    5: "splits",
    6: "financials",
    7: "balance_sheet",
    8: "cashflow",
    9: "earnings",
    10: "quarterly_earnings",
    11: "major_holders",
    12: "institutional_holders",
    13: "mutualfund_holders",
    14: "options",
    15: "option_chain",
    16: "news",
    17: "recommendations",
    18: "sustainability",
}
